#!/usr/bin/env bash

#SBATCH --job-name=evenoddsort
#SBATCH --time=10:00
# #SBATCH --ntasks=8
#SBATCH --array=1-64
#SBATCH --ntasks-per-core=1
#SBATCH --output=evenoddsort.stdout
#SBATCH --error=evenoddsort.stderr

# run on slurm: sbatch ./run

mpirun -np $SLURM_ARRAY_TASK_ID ./perf

